John Shamshoian

Homework 4

## Q1

For a multivariate count vector $\mathbf{x}=(x_1,\ldots,x_d)$ with batch size $|\mathbf{x}|=\sum_{j=1}^d x_j$, show that the probability mass function for Dirichlet-multinomial distribution is
$$
    f(\mathbf{x} \mid \alpha) 
	= \int_{\Delta_d} \binom{|\mathbf{x}|}{\mathbf{x}} \prod_{j=1}^d p_j^{x_j} \pi(\mathbf{p}) \, d \mathbf{p}  
    = \binom{|\mathbf{x}|}{\mathbf{x}} \frac{\prod_{j=1}^d \Gamma(\alpha_j+x_j)}{\prod_{j=1}^d \Gamma(\alpha_j)} \frac{\Gamma(|\alpha|)}{\Gamma(|\alpha|+|\mathbf{x}|)}
$$
where $\Delta_d$ is the unit simplex in $d$ dimensions and $|\alpha| = \sum_{j=1}^d \alpha_j$.


If $\mathbf{p} \sim \text{Dir}(\mathbf{\alpha})$, $\mathbf{p}$ is a probability density. Therefore 

$$
\int_{\Delta_d}\pi(\mathbf{p})\,d\mathbf{p} =  \int_{\Delta_d}\frac{\Gamma(|\alpha|)}{\prod_{j=1}^d \Gamma(\alpha_j)}\prod_{j=1}^d p_j^{\alpha_j-1} \, d\mathbf{p} = 1
$$

Rearranging, I get $$\int_{\Delta_d}\prod_{j=1}^d p_j^{\alpha_j-1}\,d\mathbf{p} = \frac{\prod_{j=1}^d \Gamma(\alpha_j)}{\Gamma(|\alpha|)}$$

If $\mathbf{x} \sim \text{Multinomial}(\mathbf{p})$ and $\mathbf{p} \sim \text{Dir}(\mathbf{\alpha})$, then $p(\mathbf{x}\,|\,\mathbf{p},\mathbf{\alpha}) = p(\mathbf{x}\,|\,\mathbf{p})$. Using this fact, I have

$$
\begin{align}
p(\mathbf{x}, \mathbf{p}\,|\,\mathbf{\alpha})&=\frac{p(\mathbf{x},\mathbf{p},\mathbf{\alpha})}{p(\mathbf{\alpha})}\cdot\frac{p(\mathbf{p},\mathbf{\alpha})}{p(\mathbf{p},\mathbf{\alpha})}\\\\
&= p(\mathbf{x}\,|\,\mathbf{p},\mathbf{\alpha})\cdot p(\mathbf{p}\,|\,\mathbf{\alpha})\\\\
&= p(\mathbf{x}\,|\,\mathbf{p})\cdot p(\mathbf{p}\,|\,\mathbf{\alpha})\\\\
&= \binom{|\mathbf{x}|}{\mathbf{x}} \prod_{j=1}^d p_j^{x_j} \frac{\Gamma(|\alpha|)}{\prod_{j=1}^d \Gamma(\alpha_j)} \prod_{j=1}^d p_j^{\alpha_j-1}\\\\
&= \binom{|\mathbf{x}|}{\mathbf{x}} \frac{\Gamma(|\alpha|)}{\prod_{j=1}^d \Gamma(\alpha_j)} \prod_{j=1}^d p_j^{x_j + \alpha_j-1}
\end{align}
$$

This implies 
$$
\begin{align}
p(\mathbf{x}\,|\,\mathbf{\alpha}) &= \int_{\Delta_d}p(\mathbf{x},\mathbf{p}\,|\,\mathbf{\alpha})\,d\mathbf{p}\\\\
&= \binom{|\mathbf{x}|}{\mathbf{x}} \frac{\Gamma(|\alpha|)}{\prod_{j=1}^d \Gamma(\alpha_j)}\int_{\Delta_d}\prod_{j=1}^d p_j^{x_j + \alpha_j-1}\,d\mathbf{p}\\\\
&= \binom{|\mathbf{x}|}{\mathbf{x}} \frac{\Gamma(|\alpha|)}{\prod_{j=1}^d \Gamma(\alpha_j)}\frac{\prod_{j=1}^d \Gamma(x_j+\alpha_j)}{\Gamma(|\mathbf{x}|+|\alpha|)}
\end{align}
$$

## Q2

The log-likelihood is

$$
\begin{aligned}
L(\alpha) &= \log(p(\mathbf{x}\,|\,\alpha))\\\\
&=\log\bigg[\binom{|\mathbf{x}|}{\mathbf{x}} \frac{\Gamma(|\alpha|)}{\prod_{j=1}^d \Gamma(\alpha_j)}\frac{\prod_{j=1}^d \Gamma(x_j+\alpha_j)}{\Gamma(|\mathbf{x}|+|\alpha|)}\bigg]\\\\
&=\log\bigg[\binom{|\mathbf{x}|}{\mathbf{x}}\bigg] + \log\bigg[\frac{\prod_{j=1}^{d}\Gamma(x_j+\alpha_j}{\prod_{j=1}^{d}\Gamma(\alpha_j)}\bigg] + \log\bigg[\frac{\Gamma(|\alpha|)}{\Gamma(|\mathbf{x}|+|\alpha|)}\bigg]\\\\
&=\log\bigg[\binom{|\mathbf{x}|}{\mathbf{x}}\bigg] + \sum_{j=1}^{d}\bigg[\log\Gamma(x_j+\alpha_j)-\log\Gamma(\alpha_j)\bigg] - \bigg[\log\Gamma(|x|+|\alpha|)-\log\Gamma(|\alpha|)\bigg]
\end{aligned}
$$

For indpendent $\mathbf{x_1}, \mathbf{x_2},\ldots,\mathbf{x_n}$ the log-likelihood becomes 

$$\sum_{i=1}^{n}\log\bigg[\binom{|\mathbf{x_i}|}{\mathbf{x_i}}\bigg] + \sum_{i=1}^{n}\sum_{j=1}^{d}\bigg[\log\Gamma(x_{ij}+\alpha_j)-\log\Gamma(\alpha_j)\bigg] - \sum_{i=1}^{n}\bigg[\log\Gamma(|\mathbf{x_i}|+|\alpha|)-\log\Gamma(|\alpha|)\bigg]$$


The log-likelihood is not concave. I will show the hessian matrix is not always negative definite.

$$
\begin{aligned}
\frac{d^2}{d\alpha_1^2}L(\alpha\,|\,\mathbf{x}) = \psi_1(x_1+\alpha_1)-\psi_1(\alpha_1)-\psi_1(x_1+x_2+\alpha_1+\alpha_2)+\psi_1(\alpha_1+\alpha_2)
\end{aligned}
$$

Where $\psi_1$ is the trigamma function.

Let $n=1, \alpha_1 = 10, \alpha_2=1,x_1=1,x_2=2$

In [272]:
α1 = 10
α2 = 1
x1 = 1
x2 = 2
trigamma(x1 + α1) - trigamma(α1) 
- trigamma(x1 + x2 + α1 + α2) + trigamma(α1 + α2)

0.021126067017675415

Since $\displaystyle\frac{d^2}{d\alpha_1^2}L(\alpha\,|\,\mathbf{x}) > 0$, the diagonal of the hessian is positive. Therefore the hessian is not always negative definite. The log-likelihood is not concave.

## Q3

In [3]:
"""
    dirmult_logpdf(x::Vector, α::Vector)
    
Compute the log-pdf of Dirichlet-multinomial distribution with parameter `α` 
at data point `x`.
"""
function dirmult_logpdf(x::Vector, α::Vector)
    s = 0
    result = 0
    for i in 1:length(x)
        #s += x[i]
        #result += sum(log(1:s)) - sum(log(1:x[i])) - sum(log(1:(s - x[i])))
        result += - lfact(x[i])
    end

    storage = 0
    for i in 1:length(x)
        storage += lgamma(x[i] + α[i]) - lgamma(α[i])
    end
    #print(lgamma(α[1]))
    return result + storage - lgamma(sum(α) + sum(x)) + lgamma(sum(α)) + lfact(sum(x))
end

function dirmult_logpdf!(r::Vector, X::Matrix, α::Vector)
    for j in 1:size(X, 2)
        r[j] = dirmult_logpdf(X[:, j], α)
    end
    return r
end

"""
    dirmult_logpdf(X, α)
    
Compute the log-pdf of Dirichlet-multinomial distribution with parameter `α` 
at each data point in `X`. Each column of `X` is one data point.
"""
function dirmult_logpdf(X::Matrix, α::Vector)
    r = zeros(size(X, 2))
    dirmult_logpdf!(r, X, α)
end

dirmult_logpdf

In [2]:
optdigits = readcsv("E:/Classes/BiostatisticsM280/Submissions/biostat-m280-JohnShamshoian/HW4/optdigits.tra")
training = Int64.(optdigits[:, 1:64]);
digits = Int64.(optdigits[:, 65]);

In [41]:
dirmult_logpdf(training', [1; ones(Int64, 63)])

3823-element Array{Float64,1}:
 -165.188
 -176.23 
 -167.774
 -165.564
 -157.79 
 -176.071
 -158.423
 -159.258
 -174.302
 -178.407
 -171.294
 -169.383
 -175.753
    ⋮    
 -160.49 
 -158.633
 -156.935
 -171.975
 -177.638
 -169.735
 -158.423
 -159.465
 -159.877
 -169.735
 -173.149
 -155.411

## Q5

The score function is $\nabla L(\alpha) = \displaystyle\frac{d}{d\mathbf{\alpha}}L(\alpha)$, where 

$$\displaystyle\frac{d}{d\alpha_j}L(\alpha)=\sum_{i=1}^{n}\bigg[\psi(x_{ij} + \alpha_j)-\psi(\alpha_j)\bigg]-\sum_{i=1}^{n}\bigg[\psi(|\mathbf{x_i}| + |\alpha|)-\psi(|\alpha|)\bigg]$$

$\psi$ is the digamma function.

The observed information is $-d^{2}L(\alpha)$, where

$$
\begin{aligned}
\big[-d^{2}L(\alpha))\big]_{kj} &= -\frac{d}{d\alpha_k\alpha_j}L(\alpha)\\\\
&=\begin{cases}
  \displaystyle\sum_{i=1}^{n}\bigg[\psi_{1}(|\mathbf{x_i}|+|\alpha|) - \psi_1(|\alpha|)\bigg]-\displaystyle\sum_{i=1}^{n}\bigg[\psi_{1}(x_{ij}+\alpha_j)-\psi_1(\alpha_j)\bigg] & \text{if }k = j\\\\
 \displaystyle\sum_{i=1}^{n}\bigg[\psi_{1}(|\mathbf{x_i}|+|\alpha|) - \psi_1(|\alpha|)\bigg] & \text{if }k\neq j
\end{cases}
\end{aligned}
$$

To derive the expected information matrix $\mathbb{E}[-d^{2}L(\alpha)]$ I will use the alternate form of the log-likelihood from homework 5.

$$
L(\alpha) = \sum_{i=1}^{n}\ln\binom{|\mathbf{x_i}|}{\mathbf{x_i}} + \sum_{i=1}^{n}\sum_{j=1}^{d}\sum_{k=0}^{x_{ij}-1}\ln(\alpha_j+k)-\sum_{i=1}^{n}\sum_{k=0}^{|\mathbf{x_i}|-1}\ln(|\alpha|+k)
$$

For $k\neq j$,

$$
\begin{aligned}
\mathbb{E}[-d^{2}L(\alpha)]_{kj} &=- \sum_{i=1}^{n}\sum_{x_{i1},\ldots,x_{id}}^{|\mathbf{x_i}|}\sum_{k=0}^{|\mathbf{x_i}|-1}\frac{1}{(|\alpha|+k)^2}p(\mathbf{x_i})
\end{aligned}
$$

And for $k=j$,

$$
\begin{aligned}
\mathbb{E}[-d^{2}L(\alpha)]_{kj}=\sum_{i=1}^{n}\sum_{x_{i1}\ldots,x_{id}}^{|\mathbf{x_i}|}\sum_{k=0}^{x_{ij}-1}\frac{1}{(\alpha_{j}+k)^2}p(\mathbf{x_i})-\sum_{i=1}^{n}\sum_{x_{i1}\ldots,x_{id}}^{|\mathbf{x_i}|}\sum_{k=0}^{|\mathbf{x_i}|-1}\frac{1}{(|\alpha|+k)^2}p(\mathbf{x_i})
\end{aligned}
$$

Fisher scoring is inefficient because the triple summation would take a while to compute for each iteration of the newton-raphson algorithm.

## Q6

The observed information matrix has the structure $D+11'(-p)$, where $D$ is a $d\times d$ diagonal matrix with positive entries, $p$ is a positive constant, and $1$ is a $d\times 1$ vector of ones.

$D+11'(-p)$ is positive definite if and only if $(D+11'(-p))^{-1} = D^{-1} - \displaystyle\frac{D^{-1}11'(-p)D^{-1}}{1+(-p)1'D^{-1}1} = D^{-1}+\displaystyle\frac{D^{-1}11'(p)D^{-1}}{1-p1'D^{-1}1}$ is positive definite.

From this expression I see that if $1-p1'D^{-1}1 > 0$, then $(D+11'(-p))^{-1}$ is positive definite.

In other words, the observed information matrix is positive definite if $p1'D^{-1}1<1$. If $p1'D^{-1}1\nless 1$, set $p^{*} = \displaystyle\frac{.95}{1'D^{-1}1}$. Then replace the observed information matrix with $D+11'(-p^{*})$.

## Q7

In the context of Q1, the multinomial probabilities $\mathbf{p} = (p_1,\ldots,p_{d-1})$ are random variables with $\mathbb{E}[p_i] = \displaystyle\frac{\alpha_i}{|\alpha|}$ and $Var(p_i) = \displaystyle\frac{\alpha_i(|\alpha| - \alpha_i)}{|\alpha|^2(|\alpha| +1)}$.

Also $\mathbb{E}(x_i) = \mathbf{x}\displaystyle\frac{\alpha_i}{|\alpha|}$ and $Var(X_i) = |\mathbf{x}|\displaystyle\frac{\alpha_i}{|\alpha|}\bigg(1-\frac{\alpha_i}{|\alpha|}\bigg)\bigg(\frac{|\mathbf{x}|+|\alpha|}{1+|\alpha|}\bigg) = |\mathbf{x}|\,\mathbb{E}[p_i](1-\mathbb{E}[p_i])\bigg(\frac{|\mathbf{x}|+|\alpha|}{1+|\alpha|}\bigg)$

Another result is $Cov(X_i,X_j) = -\displaystyle\frac{|\mathbf{x}|\alpha_i\alpha_j(|\mathbf{x}| + |\alpha|)}{|\alpha|^2(1+|\alpha|)} = -\mathbb{E}[p_i]\mathbb{E}[p_j]\bigg(\frac{|\mathbf{x}|+|\alpha|}{1+|\alpha|}\bigg)$

Comparing with the multinomial distribution: If $(x_1,\ldots,x_{d-1}) \sim M(p_1,\ldots,p_{d-1})$, $Var(X_i) = |\mathbf{x}|p_i(1-p_i)$ and $Cov(x_i,x_j) = -|\mathbf{x}|p_ip_j$

It follows that $\Sigma_{DM} = \displaystyle\bigg[\frac{|\mathbf{x}+|\alpha|}{1+|\alpha|}\bigg]\Sigma_M = C\Sigma_M$, where $\Sigma_{DM}$ is the covariance matrix of $\mathbf{x}$ treating $\mathbf{x}$ as dirichlet multinomial and $\Sigma_M$ is the sample covariance matrix of $\mathbf{x}$ treating $\mathbf{x}$ as multinomial.

So, $p_j$ can be estimated by $\displaystyle\frac{\sum_{i=1}^{n}x_{ij}}{\sum_{i=1}^{n}|\mathbf{x_i}|}$ and $\Sigma_{DM}$ can be estimated by $\displaystyle\frac{1}{n-1}\sum_{i=1}^{N}(\mathbf{x}_i-\overline{\mathbf{x}})(\mathbf{x}_i-\overline{\mathbf{x}})^{T}$

Solving for $C$, $\hat{C} = \displaystyle\bigg(\frac{|\hat{\Sigma}_{DM}|}{|\hat{\Sigma}_{M}|}\bigg)^{1/(k-1)}$

Since $\mathbb{E}(x_i) = \mathbf{x_i}\displaystyle\frac{\alpha_i}{|\alpha|}$, we have $\mathbb{E}[|\mathbf{\overline{x}}_i|] = \displaystyle\frac{\alpha_1}{|\alpha|}\sum_{i=1}^{n}|\mathbf{x}_i|/n$

## Q8

In [ ]:
"""
    dirmult_newton(X)

Find the MLE of Dirichlet-multinomial distribution using Newton's method.

# Argument
* `X`: an `n`-by-`d` matrix of counts; each column is one data point.

# Optional argument  
* `alpha0`: a `d` vector of starting point (optional). 
* `maxiters`: the maximum allowable Newton iterations (default 100). 
* `tolfun`: the tolerance for  relative change in objective values (default 1e-6). 

# Output
* `maximum`: the log-likelihood at MLE.   
* `estimate`: the MLE. 
* `gradient`: the gradient at MLE. 
* `hessian`: the Hessian at MLE. 
* `se`: a `d` vector of standard errors. 
* `iterations`: the number of iterations performed.
"""
function dirmult_newton(X::Matrix; α0::Vector = nothing, 
            maxiters::Int = 100, tolfun::Float64 = 1e-6)
    
    X = X[:, findnz(sum(X,1))[2]]
    p = 0
    n, m = size(X)
    # set default starting point from Q7
    α0 = ones(size(X)[2])
    gradient = zeros(m)
    D = Diagonal(zeros(m))
    H = Array(Float64, m, m)
    # Newton loop
    for iter in 1:maxiters
        for i in 1:m
            for j in 1:n
                gradient[i] = gradient[i] + digamma(X[j,i] + α0[i]) - digamma(α0[i]) - digamma(sum(X[j, :]) + sum(α0)) + digamma(sum(α0))
            end
        end
        # evaluate gradient (score)
        
        # approximated observed information matrix
        for j in 1:n
            p = p + trigamma(sum(X[j, :]) + sum(α0)) - trigamma(sum(α0))
        end
        
        p = -p
                
        for i = 1:m
            for j in 1:n   
                D[i,i] = D[i,i] + trigamma(α0[i]) - trigamma(α0[i] + X[j,i]) 
            end
        end
        
        if (1 - p * dot(ones(m), inv(D) * ones(m))) <= 0
            p = .95 * 1 / dot(ones(m), inv(D) * ones(m))
            print("hi")
        end
        
        H = D + ones(m) * ones(m)' * (-p)
        
        
        # compute Newton's direction
        
        α0 = α0 + inv(H) * gradient
        
        
            
            
        # line search loop
        for lsiter in 1:10
            # step halving
        end
        
        # check convergence criterion
        if abs(logl - loglold) < tolfun * (abs(loglold) + 1)
            break;
        end
    end
    
    # compute logl, gradient, Hessian from final iterate
    
    # output
    
end

In [20]:
size(training)

(3823,64)

In [10]:
size(training')

(64,3823)

In [25]:
m, n = size(training')
m

64

In [775]:
    digitk = training[digits .== 2, :]
X = digitk[:, findnz(sum(digitk,1))[2]]
#X = training[:, findnz(sum(training,1))[2]]
    #X = [1 2 3; 2 2 4; 1 3 5; 3 1 4]
    #X = [collect(1:10) collect(5:14) collect(10:19)]
    c = 0
    n, m = size(X)
    # set default starting point from Q7
    α0 = ones(size(X)[2])
    gradient = zeros(m)
    D = Diagonal(zeros(m))
    H = Array(Float64, m, m)

52×52 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0 

In [776]:
loglold = sum(dirmult_logpdf(X',α0))
logl = loglold
counter = 0
tolfun = 1e-6
stepsize = 1
αtemp = zeros(m)
for iter in 1:100
    loglold = logl
    gradient = zeros(m)
    D = Diagonal(zeros(m))
    H = Array(Float64, m, m)
        for j in 1:n
            for i in 1:m
                gradient[i] = gradient[i] + digamma(X[j,i] + α0[i]) - digamma(α0[i]) - digamma(sum(X[j, :]) + sum(α0)) + digamma(sum(α0))
            end
        end
        # evaluate gradient (score)
        
        # approximated observed information matrix
        for j in 1:n
            c = c + trigamma(sum(X[j, :]) + sum(α0))
        end
        
        c = c - n * trigamma(sum(α0))
                
        for i = 1:m
            for j in 1:n   
                D[i,i] = D[i,i] - trigamma(α0[i] + X[j,i]) 
            end
            D[i, i] = D[i, i] + n * trigamma(α0[i]) 
        end
        
        if (1 + c * dot(ones(m), inv(D) * ones(m))) <= 0
            c = -.95 * 1 / dot(ones(m), inv(D) * ones(m))
            print(counter,"\n")
        counter = counter + 1
        end
        H = D + ones(m) * ones(m)' * c
        
        # line search loop
        for lsiter in 1:10
            s = (2.0)^(- 2 * lsiter + 2)
            αtemp = α0 + inv(H) * gradient * s
            logltemp = sum(dirmult_logpdf(X',αtemp))
            if (logltemp > logl ) & (minimum(αtemp) > 0)
            print("hi")
                stepsize = s
                break;
            end
        end
    
        # compute Newton's direction
        
        α0 = α0 + inv(H) * gradient * stepsize
        logl = sum(dirmult_logpdf(X',α0))
        if abs(logl - loglold) < (tolfun * (abs(loglold) + 1))
            print("converged")
            break;
        end

end
#print(α0)
#print(sum(dirmult_logpdf(X', α0)))

0
hi1
hi2
hi3
hi4
hi5
hi6
hi7
hi8
hi9
hi10
hi11
hi12
hi13
hi14
hi15
hi16
hi17
hi18
hi19
hi20
hi21
hi22
hi23
hi24
hi25
hi26
hiconverged

0.015716295701320743

In [755]:
sum(dirmult_logpdf(X',α0))

-54546.20542323654

In [590]:
s = 1
        for lsiter in 1:20
            s = (2.0)^(- lsiter - 1)
            αtemp = α0 + inv(H) * gradient * s
            logltemp = sum(dirmult_logpdf(X',αtemp))
            if (logltemp > (logl + s * dot(gradient, inv(H) * gradient))) & (minimum(αtemp) > 0)
                stepsize = s
                break;
            end
        end

αtemp
    stepsize

    

0.000244140625

In [585]:
sum(dirmult_logpdf(X', α0))

-51735.148891419056

In [95]:
D = Diagonal(zeros(m))
for i = 1:m
            for j in 1:n   
                D[i,i] = D[i,i] + trigamma(α0[i]) - trigamma(α0[i] + X[j,i]) 
            end
        end
inv(D)

62×62 Diagonal{Float64}:
 0.00145156   ⋅            ⋅           …   ⋅            ⋅        
  ⋅          0.000231805   ⋅               ⋅            ⋅        
  ⋅           ⋅           0.000174492      ⋅            ⋅        
  ⋅           ⋅            ⋅               ⋅            ⋅        
  ⋅           ⋅            ⋅               ⋅            ⋅        
  ⋅           ⋅            ⋅           …   ⋅            ⋅        
  ⋅           ⋅            ⋅               ⋅            ⋅        
  ⋅           ⋅            ⋅               ⋅            ⋅        
  ⋅           ⋅            ⋅               ⋅            ⋅        
  ⋅           ⋅            ⋅               ⋅            ⋅        
  ⋅           ⋅            ⋅           …   ⋅            ⋅        
  ⋅           ⋅            ⋅               ⋅            ⋅        
  ⋅           ⋅            ⋅               ⋅            ⋅        
 ⋮                                     ⋱  ⋮                      
  ⋅           ⋅            ⋅           …   ⋅       

In [100]:
1-(p)*ones(62)'*inv(D)ones(62)

1-element Array{Float64,1}:
 106.053

In [66]:
sum(X[:,1])

0

In [430]:
X

4×3 Array{Int64,2}:
 1  2  3
 2  2  4
 1  3  5
 3  1  4

In [103]:
H = Array(Float64, m, m)

62×62 Array{Float64,2}:
   2.71456e-315  2.122e-314    …  NaN             NaN           
   2.71457e-315  0.0                0.0             2.45057e-321
   2.122e-314    0.0              NaN             NaN           
   2.71456e-315  0.0                1.92349e-315    1.9235e-315 
   2.122e-314    5.78375e-316       2.48138e-315  NaN           
   1.9235e-315   0.0           …    6.37345e-322    2.46045e-321
 NaN             2.71456e-315     NaN             NaN           
   1.92355e-315  0.0                2.4308e-321     2.77171e-321
 NaN             2.71456e-315     NaN             NaN           
   2.71456e-315  2.71456e-315       2.72724e-321  NaN           
   2.71456e-315  2.71456e-315  …    2.48138e-315  NaN           
   2.71456e-315  2.71457e-315       9.43665e-322    5.77625e-316
 NaN             2.122e-314       NaN             NaN           
   ⋮                           ⋱    ⋮                           
 NaN             2.122e-314    …  NaN             NaN           
 

In [129]:
#H = D + ones(m) * ones(m)' * p
v=.95*1.0/dot(ones(m), inv(D)*ones(m))
#eig(D+ones(m)*ones(m)'*v)
#size(D)
eig(D+ones(m)*ones(m)'*v)[1]

62-element Array{Float64,1}:
    1.28477
    3.82693
    4.40066
    5.725  
   10.5857 
   11.7259 
   36.9622 
   49.3614 
   53.4904 
   84.7534 
  152.038  
  186.813  
  255.564  
    ⋮      
 4930.06   
 4950.58   
 5029.5    
 5322.65   
 5409.45   
 5470.18   
 5474.86   
 5611.87   
 5666.37   
 5689.03   
 5731.41   
 5855.46   