In [1]:
using BenchmarkTools
srand(280) # seed
X = rand(0.0:2.0, 1000, 10000)
@benchmark A_mul_Bc(X,X)

BenchmarkTools.Trial: 
  memory estimate:  7.63 MiB
  allocs estimate:  2
  --------------
  minimum time:     115.882 ms (0.00% GC)
  median time:      128.810 ms (0.00% GC)
  mean time:        132.945 ms (0.38% GC)
  maximum time:     237.718 ms (0.00% GC)
  --------------
  samples:          38
  evals/sample:     1

In [2]:
@benchmark X * X'

BenchmarkTools.Trial: 
  memory estimate:  7.63 MiB
  allocs estimate:  2
  --------------
  minimum time:     117.541 ms (0.24% GC)
  median time:      132.309 ms (0.00% GC)
  mean time:        131.915 ms (0.39% GC)
  maximum time:     149.515 ms (0.00% GC)
  --------------
  samples:          38
  evals/sample:     1

In [3]:
@benchmark X * transpose(X)

BenchmarkTools.Trial: 
  memory estimate:  83.92 MiB
  allocs estimate:  4
  --------------
  minimum time:     246.795 ms (0.06% GC)
  median time:      271.428 ms (2.04% GC)
  mean time:        273.025 ms (3.08% GC)
  maximum time:     307.885 ms (17.67% GC)
  --------------
  samples:          19
  evals/sample:     1

In [6]:
rowdim = Int64(size(X)[1])
coldim = Int64(size(X)[2])
p = Array{Float64}(coldim)
p = sum(X, 1)
ematrix = Array{Float64}(rowdim, coldim)


1000×10000 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0 

In [8]:
@benchmark vecnorm(p)

BenchmarkTools.Trial: 
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     2.557 μs (0.00% GC)
  median time:      2.592 μs (0.00% GC)
  mean time:        2.717 μs (0.00% GC)
  maximum time:     65.691 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     9

In [9]:
ematrix = X * X' + (2 - X) * (2- X')

1000×1000 Array{Float64,2}:
 33364.0  20010.0  19950.0  19926.0  …  20050.0  19968.0  19938.0  20076.0
 20010.0  33500.0  20040.0  20016.0     19862.0  19980.0  20250.0  19980.0
 19950.0  20040.0  33378.0  19956.0     19774.0  20180.0  20116.0  19936.0
 19926.0  20016.0  19956.0  33218.0     19854.0  19784.0  20186.0  19926.0
 20042.0  19880.0  19810.0  20022.0     20062.0  19940.0  20074.0  20082.0
 19780.0  19970.0  20056.0  20168.0  …  20138.0  20078.0  19930.0  19934.0
 20026.0  20092.0  20180.0  20052.0     20134.0  20008.0  20048.0  20038.0
 19838.0  20016.0  19860.0  19858.0     20004.0  20170.0  19992.0  20056.0
 20026.0  19840.0  19936.0  20028.0     20208.0  19976.0  19970.0  20310.0
 20206.0  19928.0  20296.0  20140.0     20126.0  19938.0  20074.0  20198.0
 19896.0  19910.0  20042.0  19800.0  …  19964.0  19882.0  20096.0  19936.0
 19924.0  19922.0  20186.0  19778.0     19932.0  20058.0  20074.0  20164.0
 19954.0  19936.0  19738.0  19938.0     19708.0  20056.0  20058.0  19874

In [29]:
@benchmark 2 * X * X' + (2 - X) * (2 - X')

BenchmarkTools.Trial: 
  memory estimate:  404.36 MiB
  allocs estimate:  16
  --------------
  minimum time:     667.019 ms (9.58% GC)
  median time:      702.677 ms (12.56% GC)
  mean time:        720.875 ms (11.96% GC)
  maximum time:     894.140 ms (10.55% GC)
  --------------
  samples:          8
  evals/sample:     1

In [30]:
norm(X)

3162.178257288857

In [22]:
@benchmark 2.0 * eye(rowdim,coldim)

BenchmarkTools.Trial: 
  memory estimate:  152.62 MiB
  allocs estimate:  1993
  --------------
  minimum time:     37.894 ms (1.20% GC)
  median time:      48.180 ms (19.50% GC)
  mean time:        49.309 ms (20.28% GC)
  maximum time:     104.790 ms (64.42% GC)
  --------------
  samples:          102
  evals/sample:     1

In [26]:
fill(2.0, 1000)
@benchmark Diagonal(fill(2.0,1000))

BenchmarkTools.Trial: 
  memory estimate:  7.95 KiB
  allocs estimate:  2
  --------------
  minimum time:     600.151 ns (0.00% GC)
  median time:      1.812 μs (0.00% GC)
  mean time:        2.181 μs (28.10% GC)
  maximum time:     15.441 μs (88.87% GC)
  --------------
  samples:          10000
  evals/sample:     185

In [71]:
A = rand(10,20)
A * A'
Atemp = zeros(Float64,10,10)


function temp()
    for j = 1:10
        for k = 1:20
            for i = j:10
                Atemp[i,j] += A[i, k] * A[j, k]
            end
        end
    end
    Atemp;
end

function temp1()
    Atemp[1,1] + Atemp[1,2]
end

temp1 (generic function with 1 method)

) in module Main at In[69]:7 overwritten at In[71]:7.


In [72]:
@code_warntype temp1()

Variables:
  #self#::#temp1

Body:
  begin 
      return ((Main.getindex)(Main.Atemp,1,1)::Any + (Main.getindex)(Main.Atemp,1,2)::Any)::Any
  end::Any


In [65]:
A * A'

10×10 Array{Float64,2}:
 6.9105   4.91009  3.48595  4.17499  …  4.79823  5.585    4.76416  4.79724
 4.91009  5.86927  3.40706  3.69405     5.15505  5.64217  4.1441   4.69887
 3.48595  3.40706  3.68815  2.44277     3.61831  3.75355  3.48051  3.70234
 4.17499  3.69405  2.44277  3.72864     3.56173  3.80365  3.20248  3.36456
 4.19174  4.13183  3.49931  2.39604     3.90948  4.5534   4.63465  4.18948
 4.17151  3.8284   3.13808  3.13543  …  4.11983  4.92082  4.0137   3.84596
 4.79823  5.15505  3.61831  3.56173     5.88374  6.21947  4.55753  4.42053
 5.585    5.64217  3.75355  3.80365     6.21947  8.55216  5.47604  5.59828
 4.76416  4.1441   3.48051  3.20248     4.55753  5.47604  6.10177  4.29066
 4.79724  4.69887  3.70234  3.36456     4.42053  5.59828  4.29066  6.15424

In [57]:
A * A'

200×200 Array{Float64,2}:
 106.487   74.6009   79.1042  77.0765  …   82.6157   84.3957   79.4889
  74.6009  95.8663   68.9222  68.4148      75.8712   78.7492   73.5681
  79.1042  68.9222  101.368   74.0545      80.5421   84.2705   76.7134
  77.0765  68.4148   74.0545  93.2464      75.3223   79.6967   72.1306
  78.7937  74.5418   76.1662  69.6057      79.8632   83.084    76.398 
  75.5691  74.2434   72.6796  68.5976  …   76.8637   79.5137   77.3946
  74.8111  71.1465   76.2208  71.0065      79.536    80.8675   75.5743
  79.3259  73.864    76.1813  73.1196      83.6701   86.111    81.4285
  76.6934  73.5397   76.7322  72.4707      78.6958   84.625    78.6431
  83.6513  75.394    78.0057  73.3788      78.7023   85.1926   76.5157
  75.6485  73.3402   74.0019  68.6239  …   76.3347   82.5795   72.0812
  76.0734  72.02     76.0539  70.9211      77.4678   82.5305   76.1047
  78.538   71.7092   79.5797  73.9732      81.8422   81.9656   79.1701
   ⋮                                   ⋱           

200×200 Array{Float64,2}:
 2024.88     0.0      0.0      0.0   …     0.0      0.0      0.0      0.0 
 1418.51  1823.04     0.0      0.0         0.0      0.0      0.0      0.0 
 1504.45  1311.18  1928.15     0.0         0.0      0.0      0.0      0.0 
 1465.89  1301.18  1408.31  1773.59        0.0      0.0      0.0      0.0 
 1499.46  1418.24  1449.57  1324.83        0.0      0.0      0.0      0.0 
 1435.81  1410.62  1380.91  1303.35  …     0.0      0.0      0.0      0.0 
 1421.41  1351.78  1448.2   1349.12        0.0      0.0      0.0      0.0 
 1507.19  1403.42  1447.45  1389.27        0.0      0.0      0.0      0.0 
 1457.17  1397.25  1457.91  1376.94        0.0      0.0      0.0      0.0 
 1589.37  1432.49  1482.11  1394.2         0.0      0.0      0.0      0.0 
 1437.32  1393.46  1406.04  1303.85  …     0.0      0.0      0.0      0.0 
 1445.39  1368.38  1445.02  1347.5         0.0      0.0      0.0      0.0 
 1492.22  1362.47  1512.01  1405.49        0.0      0.0      0.0      0.0 

## Q2

0. Show the **Sherman-Morrison formula**
$$
	(\mathbf{A} + \mathbf{u} \mathbf{u}^T)^{-1} = \mathbf{A}^{-1} - \frac{1}{1 + \mathbf{u}^T \mathbf{A}^{-1} \mathbf{u}} \mathbf{A}^{-1} \mathbf{u} \mathbf{u}^T \mathbf{A}^{-1},
$$
where $\mathbf{A} \in \mathbb{R}^{n \times n}$ is nonsingular and $\mathbf{u} \in \mathbb{R}^n$. This formula supplies the inverse of the symmetric, rank-one  perturbation of $\mathbf{A}$.

0. Show the **Woodbury formula**
$$
	(\mathbf{A} + \mathbf{U} \mathbf{V}^T)^{-1} = \mathbf{A}^{-1} - \mathbf{A}^{-1} \mathbf{U} (\mathbf{I}_m + \mathbf{V}^T \mathbf{A}^{-1} \mathbf{U})^{-1} \mathbf{V}^T \mathbf{A}^{-1},
$$
where $\mathbf{A} \in \mathbb{R}^{n \times n}$ is nonsingular, $\mathbf{U}, \mathbf{V} \in \mathbb{R}^{n \times m}$, and $\mathbf{I}_m$ is the $m \times m$ identity matrix. In many applications $m$ is much smaller than $n$. Woodbury formula generalizes Sherman-Morrison and is valuable because the smaller matrix $\mathbf{I}_m + \mathbf{V}^T \mathbf{A}^{-1} \mathbf{U}$ is cheaper to invert than the larger matrix $\mathbf{A} + \mathbf{U} \mathbf{V}^T$.

0. Show the **binomial inversion formula**
$$
	(\mathbf{A} + \mathbf{U} \mathbf{B} \mathbf{V}^T)^{-1} = \mathbf{A}^{-1} - \mathbf{A}^{-1} \mathbf{U} (\mathbf{B}^{-1} + \mathbf{V}^T \mathbf{A}^{-1} \mathbf{U})^{-1} \mathbf{V}^T \mathbf{A}^{-1},
$$
where $\mathbf{A}$ and $\mathbf{B}$ are nonsingular.

0. Show the identity
$$
	\text{det}(\mathbf{A} + \mathbf{U} \mathbf{V}^T) = \text{det}(\mathbf{A}) \text{det}(\mathbf{I}_m + \mathbf{V}^T \mathbf{A}^{-1} \mathbf{U}).
$$
This formula is useful for evaluating the density of a multivariate normal with covariance matrix $\mathbf{A} + \mathbf{U} \mathbf{V}^T$.

1. Assume $(\mathbf{A} + \mathbf{uu}^{T})$ is invertible. I will show the Sherman-Morrison formula satisfies the properties of an inverse.
$$
\begin{align}
(\mathbf{A} + \mathbf{uu}^{T})\bigg(\mathbf{A}^{-1} - \frac{1}{1+\mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}}\mathbf{A}^{-1}\mathbf{uu}^{T}\mathbf{A}^{-1}\bigg) &=\mathbf{I} - \frac{\mathbf{uu}^{T}\mathbf{A}^{-1}}{1+\mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}} + \mathbf{uu}^{T}A^{-1}\mathbf{} -\frac{\mathbf{uu}^{T}\mathbf{A}^{-1}\mathbf{uu}^{T}\mathbf{A}^{-1}}{1 + \mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}}\\
&=\mathbf{I} - \frac{\mathbf{uu}^{T}\mathbf{A}^{-1}}{1+\mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}} + \frac{\mathbf{uu}^{T}A^{-1}+\mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}\mathbf{uu}^{T}\mathbf{A}^{-1}}{1+\mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}} -\frac{\mathbf{uu}^{T}\mathbf{A}^{-1}\mathbf{uu}^{T}\mathbf{A}^{-1}}{1 + \mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}}\\
&=\mathbf{I} + \frac{\mathbf{uu}^{T}\mathbf{A}^{-1}\mathbf{uu}^{T}\mathbf{A}^{-1}}{1+\mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}}-\frac{\mathbf{uu}^{T}\mathbf{A}^{-1}\mathbf{uu}^{T}\mathbf{A}^{-1}}{1 + \mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}}\\
&=\mathbf{I}
\end{align}
$$
This shows the Sherman-Morrison formula is a right-inverse. I need to check it's a left-inverse as well.
$$
\begin{align}
\bigg(\mathbf{A}^{-1} - \frac{1}{1+\mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}}\mathbf{A}^{-1}\mathbf{uu}^{T}\mathbf{A}^{-1}\bigg) (\mathbf{A} + \mathbf{uu}^{T})&=\mathbf{I} + \mathbf{A}^{-1}\mathbf{uu}^{T} - \frac{\mathbf{A}^{-1}\mathbf{uu}^{T}}{1+\mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}} - \frac{\mathbf{A}^{-1}\mathbf{uu}^{T}\mathbf{A}^{-1}\mathbf{uu}^{T}}{1+\mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}}\\
&=\mathbf{I} + \frac{\mathbf{A}^{-1}\mathbf{uu}^{T}+\mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}\mathbf{A}^{-1}\mathbf{uu}^{T}-\mathbf{A}^{-1}\mathbf{uu}^{T}-\mathbf{A}^{-1}\mathbf{uu}^{T}\mathbf{A}^{-1}\mathbf{uu}^{T}}{1+\mathbf{u}^{T}\mathbf{A}^{-1}\mathbf{u}}\\
&= \mathbf{I}
\end{align}
$$

 By definition of inverse,  $(\mathbf{A} + \mathbf{uu}^{T})^{-1}=\mathbf{A}^{-1} - \displaystyle\frac{1}{1 + \mathbf{u}^T \mathbf{A}^{-1} \mathbf{u}} \mathbf{A}^{-1} \mathbf{u} \mathbf{u}^T \mathbf{A}^{-1}$
 
2. In a similar manner,
$$
\begin{align}
(\mathbf{A} + \mathbf{UV}^{T})(\mathbf{A}^{-1} - \mathbf{A}^{-1} \mathbf{U} (\mathbf{I}_m + \mathbf{V}^T \mathbf{A}^{-1} \mathbf{U})^{-1} \mathbf{V}^T \mathbf{A}^{-1})&=\mathbf{I_n} + \mathbf{UV}^{T}\mathbf{A}^{-1}-\mathbf{U}(\mathbf{I_m}
+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}\mathbf{V}^{T}\mathbf{A}^{-1} - \mathbf{UV}^{T}\mathbf{A}^{-1}\mathbf{U}(\mathbf{I_m}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})\mathbf{V}^{T}\mathbf{A}^{-1}\\
&=\mathbf{I_n}+\mathbf{UV}^{T}\mathbf{A}^{-1}-(\mathbf{U}+\mathbf{UV}^{T}\mathbf{A}^{-1}\mathbf{U})(\mathbf{I_m}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}\mathbf{V}^{T}\mathbf{A}^{-1}\\
&=\mathbf{I_n} + \mathbf{UV}^{T}\mathbf{A}^{-1}-\mathbf{U}(\mathbf{I_m}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})(\mathbf{I_m}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}\mathbf{V}^{T}\mathbf{A}^{-1}\\
&=\mathbf{I_n}+\mathbf{UV}^{T}\mathbf{A}^{-1}-\mathbf{U}\mathbf{V}^{T}\mathbf{A}^{-1}\\
&=\mathbf{I_n}
\end{align}
$$
 
 This shows the Woodbury formula is a right inverse for $\mathbf{A} + \mathbf{UV}^{T}$. To show it's a left inverse:
$$
\begin{align}
(\mathbf{A}^{-1} - \mathbf{A}^{-1} \mathbf{U} (\mathbf{I}_m + \mathbf{V}^T \mathbf{A}^{-1} \mathbf{U})^{-1} \mathbf{V}^T \mathbf{A}^{-1})(\mathbf{A} + \mathbf{UV}^{T})&= \mathbf{I_n} + \mathbf{A}^{-1}\mathbf{UV}^{T}-\mathbf{A}^{-1}\mathbf{U}(\mathbf{I_m}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}\mathbf{V}^{T}-\mathbf{A}^{-1}\mathbf{U}(\mathbf{I_m}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{UV}^{T}\\
&=\mathbf{I_n}+\mathbf{A}^{-1}\mathbf{UV}^{T}-\mathbf{A}^{-1}\mathbf{U}(\mathbf{I_m}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}(\mathbf{V}^{T}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{UV}^{T})\\
&=\mathbf{I_n}+\mathbf{A}^{-1}\mathbf{UV}^{T}-\mathbf{A}^{-1}\mathbf{U}(\mathbf{I_m}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}(\mathbf{I_m}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})\mathbf{V}^{T}\\
&=\mathbf{I_n}+\mathbf{A}^{-1}\mathbf{UV}^{T}-\mathbf{A}^{-1}\mathbf{UV}^{T}\\
&=\mathbf{I_n}
\end{align}
$$

 By definition of inverse, $(\mathbf{A} + \mathbf{UV}^{T})^{-1}=(\mathbf{A}^{-1} - \mathbf{A}^{-1} \mathbf{U} (\mathbf{I}_m + \mathbf{V}^T \mathbf{A}^{-1} \mathbf{U})^{-1} \mathbf{V}^T \mathbf{A}^{-1})$
 
3. Continuing, 
$$
\begin{align}
(\mathbf{A}+\mathbf{UBV}^{T})(\mathbf{A}^{-1} - \mathbf{A}^{-1} \mathbf{U} (\mathbf{B}^{-1} + \mathbf{V}^T \mathbf{A}^{-1} \mathbf{U})^{-1} \mathbf{V}^T \mathbf{A}^{-1})&= \mathbf{I_n}-\mathbf{U}(\mathbf{B}^{-1}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}\mathbf{V}^{T}\mathbf{A}^{-1}+\mathbf{UBV}^{T}\mathbf{A}^{-1}-\mathbf{UBV}^{T}\mathbf{A}^{-1}\mathbf{U}(\mathbf{B}^{-1}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}\mathbf{V}^{T}\mathbf{A}^{-1}\\
&=\mathbf{I_n}+\mathbf{UBV}^{T}\mathbf{A}^{-1}-(\mathbf{U}+\mathbf{UBV}^{T}\mathbf{A}^{-1}\mathbf{U})(\mathbf{B}^{-1}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}\mathbf{V}^{T}\mathbf{A}^{-1}\\
&=\mathbf{I_n}+\mathbf{UBV}^{T}\mathbf{A}^{-1}-\mathbf{UB}(\mathbf{B}^{-1}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})(\mathbf{B}^{-1}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}\mathbf{V}^{T}\mathbf{A}^{-1}\\
&=\mathbf{I_n}+\mathbf{UBV}^{T}\mathbf{A}^{-1}-\mathbf{UBV}^{T}\mathbf{A}^{-1}\\
&=\mathbf{I_n}
\end{align}
$$

 Left inverse:
$$
\begin{align}
(\mathbf{A}^{-1} - \mathbf{A}^{-1} \mathbf{U} (\mathbf{B}^{-1} + \mathbf{V}^T \mathbf{A}^{-1} \mathbf{U})^{-1} \mathbf{V}^T \mathbf{A}^{-1})(\mathbf{A}+\mathbf{UBV}^{T})&=\mathbf{I_n} + \mathbf{A}^{-1}\mathbf{UBV}^{T}-\mathbf{A}^{-1}\mathbf{U}(\mathbf{B}^{-1}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}-\mathbf{A}^{-1}\mathbf{U}(\mathbf{B}^{-1}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{UBV}^{T}\\
&=\mathbf{I_n}+\mathbf{A}^{-1}\mathbf{UBV}^{T}-\mathbf{A}^{-1}\mathbf{U}(\mathbf{B}^{-1}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}(\mathbf{V}^{T}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{UBV}^{T})\\
&=\mathbf{I_n}+\mathbf{A}^{-1}\mathbf{UBV}^{T}-\mathbf{A}^{-1}\mathbf{U}(\mathbf{B}^{-1}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})^{-1}(\mathbf{B}^{-1}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})\mathbf{BV}^{T}\\
&=\mathbf{I_n}+\mathbf{A}^{-1}\mathbf{UBV}^{T}-\mathbf{A}^{-1}\mathbf{UBV}^{T}\\
&=\mathbf{I_n}
\end{align}
$$
 This shows $(\mathbf{A}+\mathbf{UBV}^{T})^{-1} = \mathbf{A}^{-1} - \mathbf{A}^{-1} \mathbf{U} (\mathbf{B}^{-1} + \mathbf{V}^T \mathbf{A}^{-1} \mathbf{U})^{-1} \mathbf{V}^T \mathbf{A}^{-1}$
 
4. Observate that
 $$
\begin{align}
\begin{pmatrix}\mathbf{I_n} & \mathbf{U}\\\mathbf{0_{m\times n}} & \mathbf{I_m}+\mathbf{V}^{T}\mathbf{U}\end{pmatrix} = \begin{pmatrix}\mathbf{I_n} & \mathbf{0_{n\times m}}\\\mathbf{V}^{T} & \mathbf{I_m}\end{pmatrix}\begin{pmatrix}\mathbf{I_n}+\mathbf{U}\mathbf{V}^{T} & \mathbf{U}\\\mathbf{0_{m\times n}} & \mathbf{I_m}\end{pmatrix}\begin{pmatrix}\mathbf{I_n} & \mathbf{0_{n\times m}}\\-\mathbf{V}^{T} & \mathbf{I_m}\end{pmatrix}
\end{align}
$$

 The determinant of a product is the product of determinants. Thus, $\text{det}(\mathbf{I_n} + \mathbf{UV}^{T}) = \text{det}(\mathbf{I_m}+\mathbf{V}^{T}\mathbf{U})$
 
 Therefore
$$
\begin{align}
\text{det}(\mathbf{A}+\mathbf{U}\mathbf{V}^{T}) &=\text{det}(\mathbf{A}+\mathbf{A}\mathbf{A}^{-1}\mathbf{UV}^{T})\\
&=\text{det}(\mathbf{A})\text{det}(\mathbf{I_n}+\mathbf{A}^{-1}\mathbf{UV}^{T})\\
&=\text{det}(\mathbf{A})\text{det}(\mathbf{I_m}+\mathbf{V}^{T}\mathbf{A}^{-1}\mathbf{U})
\end{align}
$$

## Q3

Consider a mixed effects model
$$
	y_i = \mathbf{x}_i^T \beta + \mathbf{z}_i^T \gamma + \epsilon_i, \quad i=1,\ldots,n,
$$
where $\epsilon_i$ are independent normal errors $N(0,\sigma_0^2)$, $\beta \in \mathbb{R}^p$ are fixed effects, and $\gamma \in \mathbb{R}^q$ are random effects assumed to be $N(\mathbf{0}_q, \sigma_1^2 \mathbf{I}_q$) independent of $\epsilon_i$. 

0. Show that 
$$
    \mathbf{y} \sim N \left( \mathbf{X} \beta, \sigma_0^2 \mathbf{I}_n + \sigma_1^2 \mathbf{Z} \mathbf{Z}^T \right),
$$
where $\mathbf{y} \in \mathbb{R}^n$, $\mathbf{X} \in \mathbb{R}^{n \times p}$, and $\mathbf{Z} \in \mathbb{R}^{n \times q}$. 

0. Write a function, with interface 
    ```julia
    logpdf_mvn(y, Z, σ0, σ1),
    ```
that evaluates the log-density of a multivariate normal with mean $\mathbf{0}$ and covariance $\sigma_0^2 \mathbf{I} + \sigma_1^2 \mathbf{Z} \mathbf{Z}^T$ at $\mathbf{y}$. Make your code efficient in the $n \gg q$ case. 

0. Compare your result (both accuracy and timing) to the [Distributions.jl](http://distributionsjl.readthedocs.io/en/latest/multivariate.html#multivariate-normal-distribution) package using following data.  
    ```julia
    using BenchmarkTools, Distributions

    srand(280)
    n, q = 2000, 10
    Z = randn(n, q)
    σ0, σ1 = 0.5, 2.0
    Σ = σ1^2 * Z * Z.' + σ0^2 * I
    mvn = MvNormal(Σ) # MVN(0, Σ)
    y = rand(mvn) # generate one instance from MNV(0, Σ)

    # check you answer matches that from Distributions.jl
    @show logpdf_mvn(y, Z, σ0, σ1)
    @show logpdf(mvn, y)

    # benchmark
    @benchmark logpdf_mvn(y, Z, σ0, σ1)
    @benchmark logpdf(mvn, y)
    ```

1. From the problem formulation, $\mathbf{Z}\gamma \sim N_n(0, \mathbf{Z}\sigma^2_1\mathbf{Z}^{T})$ and $\varepsilon \sim N_n(0,\sigma^2_0\mathbf{I_n})$ with $\mathbf{Z}\gamma$ independent of $\varepsilon$

 Let $\tilde{\varepsilon} = \mathbf{Z}\gamma + \varepsilon$. This is the sum of two independent multivariate normal variables, so $\tilde{\varepsilon} \sim N_n(0, \sigma^2_0\mathbf{I_n} + \sigma^2_1\mathbf{Z}\mathbf{Z}^{T})$
 
 Therefore $\mathbf{y} = \mathbf{X}\beta + \tilde{\varepsilon} \sim N(\mathbf{X}\beta, \sigma^2_0\mathbf{I_n} + \sigma^2_1\mathbf{Z}\mathbf{Z}^{T})$

In [38]:
# Question 3, part 2

using BenchmarkTools, Distributions

srand(280)
n, q = 2000, 10
Z = randn(n, q)
σ0, σ1 = 0.5, 2.0
Σ = σ1^2 * Z * Z.' + σ0^2 * I
mvn = MvNormal(Σ) # MVN(0, Σ)
y = rand(mvn); # generate one instance from MNV(0, Σ)

In [43]:
function logpdf_mvn(y::Array{Float64,1}, Z::Array{Float64,2}, σ0::Float64, σ1::Float64)
    k = length(y)
    
    # Save the cholesky decomposition of Σ. Cholesky decompositions are more computationally efficient
    Σchol = cholfact(Σ)
    
    # The // represent fractions in Julia.
    # The :L syntax means I want the lower triangular matrix in the cholesky decomposition
    - (k//2) * log(2π) - (1//2) * logdet(Σchol) - (1//2) * sumabs2(Σchol[:L] \ y)

end

logpdf_mvn (generic function with 2 methods)

Array{Float64, 1}, Array{Float64, 2}, Float64, Float64) in module Main at In[39]:2 overwritten at In[43]:2.


In [44]:
@show logpdf_mvn(y, Z, σ0, σ1)
@show logpdf(mvn, y)

logpdf_mvn(y,Z,σ0,σ1) = -1571.5736734654183
logpdf(mvn,y) = -1571.5736734654183


-1571.5736734654183

In [45]:
@benchmark logpdf_mvn(y, Z, σ0, σ1)

BenchmarkTools.Trial: 
  memory estimate:  61.05 MiB
  allocs estimate:  25
  --------------
  minimum time:     85.209 ms (0.76% GC)
  median time:      91.932 ms (4.92% GC)
  mean time:        94.465 ms (4.77% GC)
  maximum time:     125.584 ms (3.51% GC)
  --------------
  samples:          53
  evals/sample:     1

In [42]:
@benchmark logpdf(mvn, y)

BenchmarkTools.Trial: 
  memory estimate:  15.78 KiB
  allocs estimate:  3
  --------------
  minimum time:     5.843 ms (0.00% GC)
  median time:      5.962 ms (0.00% GC)
  mean time:        6.014 ms (0.00% GC)
  maximum time:     7.061 ms (0.00% GC)
  --------------
  samples:          826
  evals/sample:     1

In [56]:
Σchol = cholfact(Σ);
Σchol[:L] * Σchol[:U]
Σ

2000×2000 Array{Float64,2}:
  48.4398     12.5751      -1.85451   …   -0.963463     7.73531     5.55813 
  12.5751     60.0283     -43.9952         0.0624533    1.79251     8.32576 
  -1.85451   -43.9952      63.5581        -1.66745      5.60657     3.39898 
   7.47823    -6.66154      4.66697        3.53446     -1.86866     6.24601 
   3.18518    13.4341     -10.1183       -14.0829       0.217011    1.42379 
   4.58176     8.38486     14.3487    …    2.26277      1.89618    14.042   
  -9.12281   -18.4289       1.57148      -13.0892      -1.0412     -7.12815 
  -4.47219    17.7271     -30.5422         2.22316    -12.2928     -2.29981 
  -5.18916    15.2756      -2.30837       -3.42225      0.526121    5.61582 
 -10.7986      8.64372    -12.7132         3.48297     -9.16786     0.784319
 -17.8025     16.4128     -29.3033    …   13.6395     -12.5796     -5.20061 
  11.7025     -3.62996     -3.01955       -6.09396     -2.95715     1.75864 
  11.4505     16.6458      -0.157436       1.198